name: protos
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  fixnum: ^1.1.0
  protobuf: ^3.1.0
  grpc: ^3.2.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
