name: server
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  async: ^2.11.0
  protos:
    path: "../protos"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
